services:
  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:v2.3.4
    restart: always
    ports:
      - 8081:8080
    volumes:
      - lab_evolution_instances:/lab_evolution/instances
    networks:
      - lab_evolution
    env_file:
      - .env

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - lab_evolution

  django_app:
    build: ./django_project # Crie um Dockerfile neste diretório
    container_name: chatbot_manager_app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_project:/app
      - /root/chatbots:/root/chatbots # Mapeia a pasta de chatbots
      - /etc/systemd/system:/etc/systemd/system # Mapeia a pasta de serviços do systemd
    ports:
      - "8000:8000"
    depends_on:
      - postgres # Se o Django usar o mesmo banco
      - redis

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"
    networks:
      - lab_evolution

volumes:
  lab_evolution_instances:
  pg_data:

networks:
  lab_evolution:
    driver: bridge