services:
  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:v2.3.2
    restart: always
    ports:
      - 8081:8080
    volumes:
      - lab_evolution_instances:/lab_evolution/instances
    networks:
      - lab_evolution
    env_file:
      - .env

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - lab_evolution

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"
    networks:
      - lab_evolution


  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  lab_evolution_instances:
  pg_data:

networks:
  lab_evolution:
    driver: bridge