# Generated by Django 5.2.7 on 2025-10-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_update_automated_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedmessage',
            name='contact_name',
            field=models.CharField(default='teste', max_length=100, verbose_name='Nome do Contato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='automatedmessage',
            name='message',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='automatedmessage',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Número de Telefone'),
        ),
        migrations.AlterField(
            model_name='automatedmessage',
            name='send_at',
            field=models.DateTimeField(verbose_name='Data/Hora de Envio'),
        ),
        migrations.AlterField(
            model_name='botinfo',
            name='info_text',
            field=models.TextField(verbose_name='Informações do Bot'),
        ),
    ]
